name: Build Pacakge
on:
  pull_request:
    branches:
      - master
      - main
      - war-builds
    paths-ignore:
      - '**/*.yml'
      - '/pom.xml'
  
  push:
   branches:
      - master
      - main
      - war-builds
   paths-ignore:
      - '**/*.yml'
      - 'pom.xml'  
jobs:
  build:
    name: Build Package
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    - name : Variables
      run: |
         echo ${{ github.repository }}
         echo ${{ github.actor }}
         
    - uses: actions/checkout@v1
      with:
          repository: ${{ github.repository }}
          token: ${{ secrets.githubtoken }}
    - uses: actions/setup-java@v1
      with:
          java-version: '14'

    - name: Publish package
      run: |
           pwd
           #mvn -Dmaven.test.skip=true -Ddependency-check.skip=true clean compile install
           mvn -B package --file agama/pom.xml
  deploy:
    needs: [build]
    runs-on: ubuntu-latest 
    steps:
       - uses: actions/checkout@v1
       - name: Set up JDK 11
         uses: actions/setup-java@v1
         with:
          java-version: 11
       - name: Deploy to Github Package Registry
         env:
           GITHUB_USERNAME: ${{ github.actor }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           pwd
           mvn --settings settings.xml --file agama/pom.xml deploy
