name: Build Pacakge 1
on:
  pull_request:
    branches:
      - master
      - main
      - war-builds
    paths-ignore:
      - '**/*.yml'
      - 'pom.xml'
  
  push:
   branches:
      - master
      - main
      - war-builds
   paths-ignore:
      - '**/*.yml'
      - 'pom.xml'
env:
  PKG_NUMBER: "${{ github.event.repository.name }}_package_${{ github.run_number }}"
  PKG_OUTPUT_PATH: "$HOME/${{ github.event.repository.name }}_package_${{ github.run_number }}"
  
jobs:
  build:
    name: Build Package
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    - name : Variables
      run: |
         ${{ github.GITHUB_REPOSITORY }}
         
    - uses: actions/checkout@v1
      with:
          repository: ${{ github.repository }}
          token: ${{ secrets.githubtoken }}
    - uses: actions/setup-java@v1
      with:
          java-version: '14'

    - name: Publish package
      run: |
           pwd
           #mvn -Dmaven.test.skip=true -Ddependency-check.skip=true clean compile install
           mvn -B package --file agama/pom.xml
           mkdir staging
           cp -rf */*/target/*.* staging/
           
    - uses: actions/upload-artifact@v1
      with:
         name: Package
         path: staging

          
